config/routes.rb
Rails.application.routes.draw do
  
  resources :type_contracts
  resources :contracts
  resources :books
  resources :searches
  resources :appearer_searches
  
  resources :acts do
    resources :appearers
    resources :horizontal_properties
    resources :effective_possessions
    resources :documents
    resources :marginalizations
    resources :assessments
    resources :properties
  end

  devise_for :users
 

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/act.rb
class Act < ApplicationRecord
  belongs_to :user
  has_many :appearer, dependent: :destroy
  has_many :property, dependent: :destroy
  has_many :assessment, dependent: :destroy
  has_many :marginalization, dependent: :destroy
  has_many :document, dependent: :destroy
  has_many :effective_possession, dependent: :destroy
  has_many :horizontal_property, dependent: :destroy

  validates_presence_of :user_id, :descripcion, :especificacion, :tipo, :libro, :repertorio, :fecha_repertorio, :inscripcion, :fecha_inscripcion, :cuantia, :unidad
  
end

app/models/appearer.rb
class Appearer < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :tipo_persona, :razon_social, :apellido, :nombre, :tipo_interviniente, :calidad_compareciente, :tipo_identificacion, :identificacion, :estado_civil, :apellido_conyuge, :identificacion_conyuge, :separacion_bien

end

app/models/appearer_search.rb
class AppearerSearch < ApplicationRecord
  
  def search_appearers
  
    appearers = Appearer.all
    
    if apellidos.present? || nombres.present? || identificacion.present?
      appearers = appearers.where(["apellido LIKE ?", "%"+apellidos+"%"]) if apellidos.present?
      appearers = appearers.where(["nombre LIKE ?", "%"+nombres+"%"]) if nombres.present?
      appearers = appearers.where(["identificacion LIKE ?", identificacion]) if identificacion.present?
      return appearers
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :posee_gravamen, :tipo_gravamen, :genera_gravamen, :tipo_genera_gravamen, :fecha_constitucion, :fecha_cancelacion

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :descripcion
  
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  has_many :type_contract, dependent: :destroy
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :notaria, :canton, :fecha_escritura

end

app/models/marginalization.rb
class Marginalization < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :marginacion, :ultima_modificacion, :canton_registro

end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :numero_predio, :clave_catastral, :descripcion, :provincia, :zona, :superficie, :ubicacion, :lindero, :parroquia, :canton

end

app/models/search.rb
class Search < ApplicationRecord

  def search_acts
  
    acts = Act.all
    
    if repertorio.present? || repertorio.present? || inscripcion.present? || finscripcion.present?
      acts = acts.where(["repertorio = ?",repertorio]) if repertorio.present?
      acts = acts.where(["fecha_repertorio = ?",frepertorio]) if frepertorio.present?
      acts = acts.where(["inscripcion = ?", inscripcion]) if inscripcion.present?
      acts = acts.where(["fecha_inscripcion = ?", finscripcion]) if finscripcion.present?
      return acts
    end

  end

end

app/models/type_contract.rb
class TypeContract < ApplicationRecord
  belongs_to :user
  belongs_to :contract
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :act
  has_many :book
  has_many :appearer
  has_many :property
  has_many :assessment
  has_many :marginalization
  has_many :document
  has_many :effective_possession
  has_many :horizontal_property
  has_many :contract
  has_many :type_contract
  
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]
  before_action :set_act
  before_action :authenticate_user!, except: [:index, :show]

  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = current_user.assessment.new(assessment_params)
    @assessment.act = @act

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment.act, notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment.act }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment.act }
      else
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to act_path(@act), notice: 'Assessment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    def set_act
      @act = Act.find(params[:act_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assessment_params
      params.require(:assessment).permit(:user_id, :act_id, :posee_gravamen, :tipo_gravamen, :genera_gravamen, :tipo_genera_gravamen, :fecha_constitucion, :fecha_cancelacion)
    end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/appearers_helper.rb
module AppearersHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assessments/_form.html.haml
= simple_form_for [@act, @assessment], {html: { class: 'form-horizontal' }} do |f|
  -if @assessment.errors.any?
    #error_explanation
      %h3.chip
        = "#{@assessment.errors.count} errores encontrados:"
        <i class="material-icons">close</i>
      %ul
        -@assessment.errors.full_messages.each do |msg|
          %li.chip.waves-effect.waves-light.btn-large
            =msg
            <i class="material-icons">close</i>
  
  .form-group
    =f.label :posee_gravamen, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :posee_gravamen, class: "form-control", placeholder: "Posee o no Gravamen"
  .form-group
    =f.label :tipo_gravamen, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :tipo_gravamen, class: "form-control", placeholder: "Tipo de Gravamen"
  .form-group
    =f.label :genera_gravamen, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :genera_gravamen, class: "form-control", placeholder: "Genera o no Gravamen"
  .form-group
    =f.label :tipo_genera_gravamen, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :tipo_genera_gravamen, class: "form-control", placeholder: "Tipo de Gravamen que genera"
  .form-group
    =f.label :fecha_constitucion, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :fecha_constitucion, class: "form-control", html5: true
  .form-group
    =f.label :fecha_cancelacion, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :fecha_cancelacion, class: "form-control", html5: true

  .form-group
    .row.center-xs
      .col-xs-5
        = f.button :submit, class: "btn btn-raised btn-info btn-lg", value: "Guardar"

app/views/assessments/edit.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel.posicion
    .row.height-panel.middle-xs
      .col-xs-2.fijo
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_act_path
                  %li.divider
                  %li
                    =link_to "Ver", acts_path
              %li.divider
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Búsqueda
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Inscripción", new_search_path
                  %li.divider
                  %li
                    =link_to "Compareciente", new_appearer_search_path
              %li.divider
              -if current_user
                %li
                  =link_to "Perfil", edit_user_registration_path
                %li
                  =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.derecha
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Editar Gravamen
            .panel-body
              = render 'form'
              = link_to 'Regresar', @act

app/views/assessments/index.html.haml
%h1 Listing assessments

%table
  %thead
    %tr
      %th User
      %th Act
      %th Posee gravamen
      %th Tipo gravamen
      %th Genera gravamen
      %th Tipo genera gravamen
      %th Fecha constitucion
      %th Fecha cancelacion
      %th
      %th
      %th

  %tbody
    - @assessments.each do |assessment|
      %tr
        %td= assessment.user
        %td= assessment.act
        %td= assessment.posee_gravamen
        %td= assessment.tipo_gravamen
        %td= assessment.genera_gravamen
        %td= assessment.tipo_genera_gravamen
        %td= assessment.fecha_constitucion
        %td= assessment.fecha_cancelacion
        %td= link_to 'Show', assessment
        %td= link_to 'Edit', edit_assessment_path(assessment)
        %td= link_to 'Destroy', assessment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/assessments/new.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel.posicion
    .row.height-panel.middle-xs
      .col-xs-2.fijo
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_act_path
                  %li.divider
                  %li
                    =link_to "Ver", acts_path
              %li.divider
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Búsqueda
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Inscripción", new_search_path
                  %li.divider
                  %li
                    =link_to "Compareciente", new_appearer_search_path
              %li.divider
              -if current_user
                %li
                  =link_to "Perfil", edit_user_registration_path
                %li
                  =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.derecha
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Nuevo Gravamen
            .panel-body
              = render 'form'
              = link_to 'Back', act_path(@act)

app/views/assessments/show.html.haml
%p#notice= notice

%p
  %b User:
  = @assessment.user
%p
  %b Act:
  = @assessment.act
%p
  %b Posee gravamen:
  = @assessment.posee_gravamen
%p
  %b Tipo gravamen:
  = @assessment.tipo_gravamen
%p
  %b Genera gravamen:
  = @assessment.genera_gravamen
%p
  %b Tipo genera gravamen:
  = @assessment.tipo_genera_gravamen
%p
  %b Fecha constitucion:
  = @assessment.fecha_constitucion
%p
  %b Fecha cancelacion:
  = @assessment.fecha_cancelacion

= link_to 'Edit', edit_assessment_path(@assessment)
\|
= link_to 'Back', assessments_path