config/routes.rb
Rails.application.routes.draw do
  
  resources :type_contracts
  resources :contracts
  resources :books
  resources :searches
  resources :appearer_searches
  
  resources :acts do
    resources :appearers
    resources :horizontal_properties
    resources :effective_possessions
    resources :documents
    resources :marginalizations
    resources :assessments
    resources :properties
  end

  devise_for :users
 

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/act.rb
class Act < ApplicationRecord
  belongs_to :user
  has_many :appearer, dependent: :destroy
  has_many :property, dependent: :destroy
  has_many :assessment, dependent: :destroy
  has_many :marginalization, dependent: :destroy
  has_many :document, dependent: :destroy
  has_many :effective_possession, dependent: :destroy
  has_many :horizontal_property, dependent: :destroy

  validates_presence_of :user_id, :descripcion, :especificacion, :tipo, :libro, :repertorio, :fecha_repertorio, :inscripcion, :fecha_inscripcion, :cuantia, :unidad
  
end

app/models/appearer.rb
class Appearer < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :tipo_persona, :razon_social, :apellido, :nombre, :tipo_interviniente, :calidad_compareciente, :tipo_identificacion, :identificacion, :estado_civil, :apellido_conyuge, :identificacion_conyuge, :separacion_bien

end

app/models/appearer_search.rb
class AppearerSearch < ApplicationRecord
  
  def search_appearers
  
    appearers = Appearer.all
    
    if apellidos.present? || nombres.present? || identificacion.present?
      appearers = appearers.where(["apellido LIKE ?", "%"+apellidos+"%"]) if apellidos.present?
      appearers = appearers.where(["nombre LIKE ?", "%"+nombres+"%"]) if nombres.present?
      appearers = appearers.where(["identificacion LIKE ?", identificacion]) if identificacion.present?
      return appearers
    end

  end

end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :posee_gravamen, :tipo_gravamen, :genera_gravamen, :tipo_genera_gravamen, :fecha_constitucion, :fecha_cancelacion

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :descripcion
  
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  has_many :type_contract, dependent: :destroy
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :notaria, :canton, :fecha_escritura

end

app/models/horizontal_property.rb
class HorizontalProperty < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :propiedad, :alicuota, :expensas, :comparece_menor, :nombres_tutor, :fecha_adjudicacion, :fecha_acta_notarial

end

app/models/marginalization.rb
class Marginalization < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :marginacion, :ultima_modificacion, :canton_registro

end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :numero_predio, :clave_catastral, :descripcion, :provincia, :zona, :superficie, :ubicacion, :lindero, :parroquia, :canton

end

app/models/search.rb
class Search < ApplicationRecord

  def search_acts
  
    acts = Act.all
    
    if repertorio.present? || repertorio.present? || inscripcion.present? || finscripcion.present?
      acts = acts.where(["repertorio = ?",repertorio]) if repertorio.present?
      acts = acts.where(["fecha_repertorio = ?",frepertorio]) if frepertorio.present?
      acts = acts.where(["inscripcion = ?", inscripcion]) if inscripcion.present?
      acts = acts.where(["fecha_inscripcion = ?", finscripcion]) if finscripcion.present?
      return acts
    end

  end

end

app/models/type_contract.rb
class TypeContract < ApplicationRecord
  belongs_to :user
  belongs_to :contract
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :act
  has_many :book
  has_many :appearer
  has_many :property
  has_many :assessment
  has_many :marginalization
  has_many :document
  has_many :effective_possession
  has_many :horizontal_property
  has_many :contract
  has_many :type_contract
  
end

app/controllers/horizontal_properties_controller.rb
class HorizontalPropertiesController < ApplicationController
  before_action :set_horizontal_property, only: [:show, :edit, :update, :destroy]
  before_action :set_act
  before_action :authenticate_user!, except: [:index, :show]

  # GET /horizontal_properties
  # GET /horizontal_properties.json
  def index
    @horizontal_properties = HorizontalProperty.all
  end

  # GET /horizontal_properties/1
  # GET /horizontal_properties/1.json
  def show
  end

  # GET /horizontal_properties/new
  def new
    @horizontal_property = HorizontalProperty.new
  end

  # GET /horizontal_properties/1/edit
  def edit
  end

  # POST /horizontal_properties
  # POST /horizontal_properties.json
  def create
    @horizontal_property = current_user.horizontal_property.new(horizontal_property_params)
    @horizontal_property.act = @act

    respond_to do |format|
      if @horizontal_property.save
        format.html { redirect_to @horizontal_property.act, notice: 'Horizontal property was successfully created.' }
        format.json { render :show, status: :created, location: @horizontal_property.act }
      else
        format.html { render :new }
        format.json { render json: @horizontal_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horizontal_properties/1
  # PATCH/PUT /horizontal_properties/1.json
  def update
    respond_to do |format|
      if @horizontal_property.update(horizontal_property_params)
        format.html { redirect_to @horizontal_property.act, notice: 'Horizontal property was successfully updated.' }
        format.json { render :show, status: :ok, location: @horizontal_property.act }
      else
        format.html { render :edit }
        format.json { render json: @horizontal_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horizontal_properties/1
  # DELETE /horizontal_properties/1.json
  def destroy
    @horizontal_property.destroy
    respond_to do |format|
      format.html { redirect_to act_path(@act), notice: 'Horizontal property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horizontal_property
      @horizontal_property = HorizontalProperty.find(params[:id])
    end

    def set_act
      @act = Act.find(params[:act_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horizontal_property_params
      params.require(:horizontal_property).permit(:user_id, :act_id, :propiedad, :alicuota, :expensas, :comparece_menor, :nombres_tutor, :fecha_adjudicacion, :fecha_acta_notarial)
    end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/appearers_helper.rb
module AppearersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/horizontal_properties_helper.rb
module HorizontalPropertiesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/horizontal_properties/_form.html.haml
= simple_form_for [@act, @horizontal_property], {html: { class: 'form-horizontal' }} do |f|
  -if @horizontal_property.errors.any?
    #error_explanation
      %h3.chip
        = "#{@horizontal_property.errors.count} errores encontrados:"
        <i class="material-icons">close</i>
      %ul
        -@horizontal_property.errors.full_messages.each do |msg|
          %li.chip.waves-effect.waves-light.btn-large
            =msg
            <i class="material-icons">close</i>


  .form-group
    =f.label :propiedad, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :propiedad, class: "form-control", placeholder: "Es Propiedad Horizontal"
  .form-group
    =f.label :alicuota, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :alicuota, class: "form-control", placeholder: "Porcentaje de Alícuota"
  .form-group
    =f.label :expensas, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :expensas, class: "form-control", placeholder: "Certificado o Declaración"
  .form-group
    =f.label :comparece_menor, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :comparece_menor, class: "form-control", placeholder: "Comparece Menores de Edad"
  .form-group
    =f.label :nombres_tutor, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :nombres_tutor, class: "form-control", placeholder: "Nombres y Apellidos del Tutor"
  .form-group
    =f.label :fecha_adjudicacion, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :fecha_adjudicacion, class: "form-control", html5: true
  .form-group
    =f.label :fecha_acta_notarial, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :fecha_acta_notarial, class: "form-control", html5: true
  
  .form-group
    .row.center-xs
      .col-xs-5
        = f.button :submit, class: "btn btn-raised btn-info btn-lg", value: "Guardar"

app/views/horizontal_properties/edit.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel.posicion
    .row.height-panel.middle-xs
      .col-xs-2.fijo
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_act_path
                  %li.divider
                  %li
                    =link_to "Ver", acts_path
              %li.divider
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Búsqueda
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Inscripción", new_search_path
                  %li.divider
                  %li
                    =link_to "Compareciente", new_appearer_search_path
              %li.divider
              -if current_user
                %li
                  =link_to "Perfil", edit_user_registration_path
                %li
                  =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.derecha
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Editar Propiedad Horizontal
            .panel-body
              = render 'form'
              = link_to 'Back', act_path(@act)

app/views/horizontal_properties/index.html.haml
%h1 Listing horizontal_properties

%table
  %thead
    %tr
      %th User
      %th Act
      %th Propiedad
      %th Alicuota
      %th Expensas
      %th Comparece menor
      %th Nombres tutor
      %th Fecha adjudicacion
      %th Fecha acta notarial
      %th
      %th
      %th

  %tbody
    - @horizontal_properties.each do |horizontal_property|
      %tr
        %td= horizontal_property.user
        %td= horizontal_property.act
        %td= horizontal_property.propiedad
        %td= horizontal_property.alicuota
        %td= horizontal_property.expensas
        %td= horizontal_property.comparece_menor
        %td= horizontal_property.nombres_tutor
        %td= horizontal_property.fecha_adjudicacion
        %td= horizontal_property.fecha_acta_notarial
        %td= link_to 'Show', horizontal_property
        %td= link_to 'Edit', edit_horizontal_property_path(horizontal_property)
        %td= link_to 'Destroy', horizontal_property, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Horizontal property', new_horizontal_property_path

app/views/horizontal_properties/new.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel.posicion
    .row.height-panel.middle-xs
      .col-xs-2.fijo
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_act_path
                  %li.divider
                  %li
                    =link_to "Ver", acts_path
              %li.divider
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Búsqueda
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Inscripción", new_search_path
                  %li.divider
                  %li
                    =link_to "Compareciente", new_appearer_search_path
              %li.divider
              -if current_user
                %li
                  =link_to "Perfil", edit_user_registration_path
                %li
                  =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.derecha
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Nueva Propiedad Horizontal
            .panel-body
              = render 'form'
              = link_to 'Back', act_path(@act)

app/views/horizontal_properties/show.html.haml
%p#notice= notice

%p
  %b User:
  = @horizontal_property.user
%p
  %b Act:
  = @horizontal_property.act
%p
  %b Propiedad:
  = @horizontal_property.propiedad
%p
  %b Alicuota:
  = @horizontal_property.alicuota
%p
  %b Expensas:
  = @horizontal_property.expensas
%p
  %b Comparece menor:
  = @horizontal_property.comparece_menor
%p
  %b Nombres tutor:
  = @horizontal_property.nombres_tutor
%p
  %b Fecha adjudicacion:
  = @horizontal_property.fecha_adjudicacion
%p
  %b Fecha acta notarial:
  = @horizontal_property.fecha_acta_notarial

= link_to 'Edit', edit_horizontal_property_path(@horizontal_property)
\|
= link_to 'Back', horizontal_properties_path