config/routes.rb
Rails.application.routes.draw do
  
  resources :type_contracts
  resources :contracts
  resources :books
  resources :searches
  resources :appearer_searches
  
  resources :acts do
    resources :appearers
    resources :horizontal_properties
    resources :effective_possessions
    resources :documents
    resources :marginalizations
    resources :assessments
    resources :properties
  end

  devise_for :users
 

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/act.rb
class Act < ApplicationRecord
  belongs_to :user
  has_many :appearer, dependent: :destroy
  has_many :property, dependent: :destroy
  has_many :assessment, dependent: :destroy
  has_many :marginalization, dependent: :destroy
  has_many :document, dependent: :destroy
  has_many :effective_possession, dependent: :destroy
  has_many :horizontal_property, dependent: :destroy

  validates_presence_of :user_id, :descripcion, :especificacion, :tipo, :libro, :repertorio, :fecha_repertorio, :inscripcion, :fecha_inscripcion, :cuantia, :unidad
  
end

app/models/appearer.rb
class Appearer < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :tipo_persona, :razon_social, :apellido, :nombre, :tipo_interviniente, :calidad_compareciente, :tipo_identificacion, :identificacion, :estado_civil, :apellido_conyuge, :identificacion_conyuge, :separacion_bien

end

app/models/appearer_search.rb
class AppearerSearch < ApplicationRecord
  
  def search_appearers
  
    appearers = Appearer.all
    
    if apellidos.present? || nombres.present? || identificacion.present?
      appearers = appearers.where(["apellido LIKE ?", "%"+apellidos+"%"]) if apellidos.present?
      appearers = appearers.where(["nombre LIKE ?", "%"+nombres+"%"]) if nombres.present?
      appearers = appearers.where(["identificacion LIKE ?", identificacion]) if identificacion.present?
      return appearers
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :posee_gravamen, :tipo_gravamen, :genera_gravamen, :tipo_genera_gravamen, :fecha_constitucion, :fecha_cancelacion

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :descripcion
  
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  has_many :type_contract, dependent: :destroy
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :notaria, :canton, :fecha_escritura

end

app/models/marginalization.rb
class Marginalization < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :marginacion, :ultima_modificacion, :canton_registro

end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :act

  validates_presence_of :user_id, :act_id, :numero_predio, :clave_catastral, :descripcion, :provincia, :zona, :superficie, :ubicacion, :lindero, :parroquia, :canton

end

app/models/search.rb
class Search < ApplicationRecord

  def search_acts
  
    acts = Act.all
    
    if repertorio.present? || repertorio.present? || inscripcion.present? || finscripcion.present?
      acts = acts.where(["repertorio = ?",repertorio]) if repertorio.present?
      acts = acts.where(["fecha_repertorio = ?",frepertorio]) if frepertorio.present?
      acts = acts.where(["inscripcion = ?", inscripcion]) if inscripcion.present?
      acts = acts.where(["fecha_inscripcion = ?", finscripcion]) if finscripcion.present?
      return acts
    end

  end

end

app/models/type_contract.rb
class TypeContract < ApplicationRecord
  belongs_to :user
  belongs_to :contract
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :act
  has_many :book
  has_many :appearer
  has_many :property
  has_many :assessment
  has_many :marginalization
  has_many :document
  has_many :effective_possession
  has_many :horizontal_property
  has_many :contract
  has_many :type_contract
  
end

app/controllers/marginalizations_controller.rb
class MarginalizationsController < ApplicationController
  before_action :set_marginalization, only: [:show, :edit, :update, :destroy]
  before_action :set_act
  before_action :authenticate_user!, except: [:index, :show]

  # GET /marginalizations
  # GET /marginalizations.json
  def index
    @marginalizations = Marginalization.all
  end

  # GET /marginalizations/1
  # GET /marginalizations/1.json
  def show
  end

  # GET /marginalizations/new
  def new
    @marginalization = Marginalization.new
  end

  # GET /marginalizations/1/edit
  def edit
  end

  # POST /marginalizations
  # POST /marginalizations.json
  def create
    @marginalization = current_user.marginalization.new(marginalization_params)
    @marginalization.act = @act 

    respond_to do |format|
      if @marginalization.save
        format.html { redirect_to @marginalization.act, notice: 'Marginalization was successfully created.' }
        format.json { render :show, status: :created, location: @marginalization.act }
      else
        format.html { render :new }
        format.json { render json: @marginalization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marginalizations/1
  # PATCH/PUT /marginalizations/1.json
  def update
    respond_to do |format|
      if @marginalization.update(marginalization_params)
        format.html { redirect_to @marginalization.act, notice: 'Marginalization was successfully updated.' }
        format.json { render :show, status: :ok, location: @marginalization.act }
      else
        format.html { render :edit }
        format.json { render json: @marginalization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marginalizations/1
  # DELETE /marginalizations/1.json
  def destroy
    @marginalization.destroy
    respond_to do |format|
      format.html { redirect_to act_path(@act), notice: 'Marginalization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marginalization
      @marginalization = Marginalization.find(params[:id])
    end

    def set_act
      @act = Act.find(params[:act_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marginalization_params
      params.require(:marginalization).permit(:user_id, :act_id, :marginacion, :ultima_modificacion, :canton_registro)
    end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/appearers_helper.rb
module AppearersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/marginalizations_helper.rb
module MarginalizationsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/marginalizations/_form.html.haml
= simple_form_for [@act, @marginalization], {html: { class: 'form-horizontal' }} do |f|
  -if @marginalization.errors.any?
    #error_explanation
      %h3.chip
        = "#{@marginalization.errors.count} errores encontrados:"
        <i class="material-icons">close</i>
      %ul
        -@marginalization.errors.full_messages.each do |msg|
          %li.chip.waves-effect.waves-light.btn-large
            =msg
            <i class="material-icons">close</i>
  
  .form-group
    =f.label :marginacion, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :marginacion, class: "form-control", placeholder: "Trámite orginal al que se debe afectar su estado"
  .form-group
    =f.label :ultima_modificacion, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :ultima_modificacion, class: "form-control", html5: true
  .form-group
    =f.label :canton_registro, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :canton_registro, class: "form-control", placeholder: "Cantón del Regostro de la Propiedad"

  .form-group
    .row.center-xs
      .col-xs-5
        = f.button :submit, class: "btn btn-raised btn-info btn-lg", value: "Guardar"

app/views/marginalizations/edit.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel.posicion
    .row.height-panel.middle-xs
      .col-xs-2.fijo
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_act_path
                  %li.divider
                  %li
                    =link_to "Ver", acts_path
              %li.divider
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Búsqueda
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Inscripción", new_search_path
                  %li.divider
                  %li
                    =link_to "Compareciente", new_appearer_search_path
              %li.divider
              -if current_user
                %li
                  =link_to "Perfil", edit_user_registration_path
                %li
                  =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.derecha
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Editar Marginación
            .panel-body
              = render 'form'
              = link_to 'Regresar', @act

app/views/marginalizations/index.html.haml
%h1 Listing marginalizations

%table
  %thead
    %tr
      %th User
      %th Act
      %th Marginacion
      %th Ultima modificacion
      %th Canton registro
      %th
      %th
      %th

  %tbody
    - @marginalizations.each do |marginalization|
      %tr
        %td= marginalization.user
        %td= marginalization.act
        %td= marginalization.marginacion
        %td= marginalization.ultima_modificacion
        %td= marginalization.canton_registro
        %td= link_to 'Show', marginalization
        %td= link_to 'Edit', edit_marginalization_path(marginalization)
        %td= link_to 'Destroy', marginalization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Marginalization', new_marginalization_path

app/views/marginalizations/new.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel.posicion
    .row.height-panel.middle-xs
      .col-xs-2.fijo
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_act_path
                  %li.divider
                  %li
                    =link_to "Ver", acts_path
              %li.divider
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Búsqueda
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Inscripción", new_search_path
                  %li.divider
                  %li
                    =link_to "Compareciente", new_appearer_search_path
              %li.divider
              -if current_user
                %li
                  =link_to "Perfil", edit_user_registration_path
                %li
                  =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.derecha
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Nueva Marginación
            .panel-body
              = render 'form'
              = link_to 'Back', act_path(@act)

app/views/marginalizations/show.html.haml
%p#notice= notice

%p
  %b User:
  = @marginalization.user
%p
  %b Act:
  = @marginalization.act
%p
  %b Marginacion:
  = @marginalization.marginacion
%p
  %b Ultima modificacion:
  = @marginalization.ultima_modificacion
%p
  %b Canton registro:
  = @marginalization.canton_registro

= link_to 'Edit', edit_marginalization_path(@marginalization)
\|
= link_to 'Back', marginalizations_path